### ISSUE TITLE
could not determine kind of name for C.pango_attr_insert_hyphens_new

### ISSUE THREAD

**Issue by sunshine69** [linuxerwang/sourceview3#1]
Hi there

I just tried based on the instructions and got error

```
could not determine kind of name for C.pango_attr_insert_hyphens_new
```

not sure which depends should I need?

**Comment by linuxerwang** [comment]
You need gotk3 at https://github.com/gotk3/gotk3. Follow the instruction there to install.

**Comment by sunshine69** [comment]
Thanks but I already got it installed.

I have an app https://github.com/sunshine69/gnote and building is fine - that is I have a working gotk3 locally. I am trying to add gtksource view into the app and I got the error.

**Comment by linuxerwang** [comment]
I created a pull request #5. It's just a demo, you don't need to merge it. Most of the line changes are from my VSCode auto formatting, thus can be ignored. The demo enables markdown language, so you can verify it with markdown text, as the attached screenshot
![Screenshot from 2020-12-27 21-28-05](https://user-images.githubusercontent.com/3304478/103191646-8e98d700-488a-11eb-9de4-296b175bf468.png)
.

**Comment by sunshine69** [comment]
Thanks, it must be something in my env to build it and got error. When I have a chance I will try your PR to build and see if it works. Which command you used to build or you use my existing build script ?

**Comment by linuxerwang** [comment]
I used the same commands you put in the README.md.

**Comment by sunshine69** [comment]
I can build your branch in my machine which is great. Thanks. I will use that to build some more features to be able to switch between textview and sourceview using config and avoid the current code hightlight interfere with sourceview when source view is in used thus I probably wont merge your branch but will use the sample in a different way. It looks like sourceview increase memory usage around 15M so better to have an option for a very low resource machine and when the use of sourceview is not needed.
